name: Notes

on:
  push:
    tags:
      - "v*.*.*"  # run only when a version tag is pushed

permissions:
  contents: read

jobs:
  notes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Sync notes
        uses: ./.github/actions/notes-sync
        with:
          subset: all
