name: Release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/make-release
        with:
          out: build
          tag: ${{ github.ref_name }}

      - name: Upload assets
        uses: actions/upload-artifact@v4
        with:
          name: release-assets
          path: build/*

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: build/*
