name: Build & attach EPUB on tag

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Pandoc
        run: sudo apt-get update && sudo apt-get install -y pandoc

    - name: Build EPUB
  run: |
    mkdir -p build
    TAG="$(git describe --tags --exact-match 2>/dev/null || echo "")"
    SHORT_SHA="$(git rev-parse --short HEAD)"
    # Prefer tag; fall back to short SHA
    VERSION="${TAG:-commit-${SHORT_SHA}}"
    PUBLISH_DATE="$(date -u +'%Y-%m-%d')"   # ISO date

    pandoc manuscript/*.md \
      --metadata-file=metadata.yaml \
      --metadata=version="${VERSION}" \
      --metadata=date="${PUBLISH_DATE}" \
      --resource-path=manuscript:images \
      --toc \
      --epub-cover-image=images/battery.png \
      -o build/Blackout_Weak_Signals.epub


      - name: Create GitHub Release (if not exists) and upload asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: build/${{ env.OUT }}
