name: Build & attach EPUB on tag

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

permissions:
  contents: write

env:
  OUT: Blackout_Weak_Signals.epub

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Prefer the official setup to apt (newer Pandoc, faster)
      - name: Setup Pandoc
        uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: "3.1.11"

      - name: Build EPUB
        shell: bash
        run: |
          mkdir -p build
          SHORT_SHA="$(git rev-parse --short HEAD)"

          # Only treat ref name as a version if this is a tag push
          if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
            VERSION="${GITHUB_REF_NAME}"
          else
            VERSION="commit-${SHORT_SHA}"
          fi

          # ISO date in UTC for reproducibility
          PUBLISH_DATE="$(date -u +'%Y-%m-%d')"

          pandoc manuscript/*.md \
            --from=markdown \
            --toc --toc-depth=2 \
            --metadata-file=metadata.yaml \
            --metadata=version="${VERSION}" \
            --metadata=date="${PUBLISH_DATE}" \
            --resource-path=.:manuscript:images \
            --epub-cover-image=images/cover.png \
            -o "build/${OUT}"

          ls -lh build

      - name: Create GitHub Release and upload asset
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: build/${{ env.OUT }}
